#include "GlobalStateManager.h"
#include "Column.h"
#include <stdexcept>
#include <string>

GlobalStateManager::GlobalStateManager(int num_trains, int num_arcs):
num_trains_(num_trains),
num_arcs_(num_arcs),
flat_arc_to_columns_(num_arcs * num_trains), 
flat_is_forbidden_(num_trains * num_arcs, false) {}

bool GlobalStateManager::is_arc_forbidden(int train_id, int arc_id) const{
    train_id --;
    return flat_is_forbidden_[train_id * num_arcs_ + arc_id];
}

//Precondition : the added column should be associated with a path without active restriction (ie we can initialize conflict_count to be 0)
//It is coherent with the fact that column are only generated by the pricer which should only use non forbidden arcs
void GlobalStateManager::register_column(const Column& col){
     for(int arc_id : col.arc_ids){
        flat_arc_to_columns_[num_arcs_* (col.train_id -1) + arc_id].push_back(col.ID);
     }

     if(conflict_count_.size() != static_cast<size_t>(col.ID)){
        throw std::runtime_error("The number of column tracked by the State Manager is incoherent with the current column id. ID to add is :" 
                                 + std::to_string(col.ID) + " expected : " + std::to_string(conflict_count_.size()));
     }
     conflict_count_.push_back(0);
}

ColumnList GlobalStateManager::apply_delta(int train_id, const std::vector<int>& forbidden_arcs){
    train_id --;
    ColumnList to_remove{};
    for(int arc_id: forbidden_arcs){
        flat_is_forbidden_[num_arcs_ * train_id + arc_id] = true;
        for(int column_id: flat_arc_to_columns_[num_arcs_ * train_id + arc_id]){
            if(conflict_count_[column_id] == 0){
                to_remove.push_back(column_id);
            }
            conflict_count_[column_id]++;
        }
    }
    return to_remove;
}

ColumnList GlobalStateManager::revert_delta(int train_id, const std::vector<int>& forbidden_arcs){
    train_id--;
    ColumnList to_add_back{};
    for(int arc_id: forbidden_arcs){
        flat_is_forbidden_[num_arcs_ * train_id + arc_id] = false;
        for(int column_id: flat_arc_to_columns_[num_arcs_* train_id + arc_id]){
            conflict_count_[column_id]--;
            if(conflict_count_[column_id] == 0){
                to_add_back.push_back(column_id);
            }
        }
    }
    return to_add_back;
}



